// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNTrHV_FI5WbjbM28_R3YcHRGjKpVLV04',
    appId: '1:73735196282:web:dddc57b374df958a99b5c3',
    messagingSenderId: '73735196282',
    projectId: 'arac-kiralama-ac17a',
    authDomain: 'arac-kiralama-ac17a.firebaseapp.com',
    storageBucket: 'arac-kiralama-ac17a.firebasestorage.app',
    measurementId: 'G-2QG5VZM4DJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0jcslkyQ3swbznCVzRZmU05pIWjB-Zk',
    appId: '1:73735196282:android:00e6d51ea81d80e599b5c3',
    messagingSenderId: '73735196282',
    projectId: 'arac-kiralama-ac17a',
    storageBucket: 'arac-kiralama-ac17a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcHpX9US6OxOTKWhcfwApQHaBBpmn_PIU',
    appId: '1:73735196282:ios:53ad16d8cfb56bf399b5c3',
    messagingSenderId: '73735196282',
    projectId: 'arac-kiralama-ac17a',
    storageBucket: 'arac-kiralama-ac17a.firebasestorage.app',
    iosBundleId: 'com.example.flutterLoginDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNTrHV_FI5WbjbM28_R3YcHRGjKpVLV04',
    appId: '1:73735196282:web:a836111d1688664799b5c3',
    messagingSenderId: '73735196282',
    projectId: 'arac-kiralama-ac17a',
    authDomain: 'arac-kiralama-ac17a.firebaseapp.com',
    storageBucket: 'arac-kiralama-ac17a.firebasestorage.app',
    measurementId: 'G-JHC4VPWSP5',
  );
}
